# Generated by Django 5.2.7 on 2025-12-31 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Emp_Id', models.IntegerField()),
                ('Dept', models.CharField(max_length=50)),
                ('Phone_No', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='principles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Emp_Id', models.IntegerField()),
                ('Phone_No', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Join_Date', models.DateField()),
                ('End_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='profissors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Emp_Id', models.IntegerField()),
                ('Subj', models.CharField(max_length=50)),
                ('Phone_No', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Roll_No', models.IntegerField()),
                ('year', models.CharField(max_length=10)),
                ('Phone_No', models.BigIntegerField()),
                ('select', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.profissors')),
            ],
        ),
    ]
